### ISSUE TITLE
Implement KD-Tree

### ISSUE THREAD

**Issue by blacklab** [blacklab/renderer#29]
Implement http://dcgi.felk.cvut.cz/home/havran/ARTICLES/ingo06rtKdtree.pdf

**Comment by boxdot** [comment]
Implemented Triangle AABB intersection test need for KDTree according to "Fast 3D Triangle-Box Overlap Testing" by Tomas Adenine-Möller.

**Comment by boxdot** [comment]
Basic skeleton of kd tree is implemented. The surface area heuristic cost function is also there. To continue, I need a _fast_ algorithm for clipping a triangle against an AABB. Another AABB as the result of the algorithm would be enough; I don't need the exact result of the clipping.

**Comment by boxdot** [comment]
Implemented Cohen–Sutherland line clipping algorithm. Used it to implement triangle aabb clipping. Not sure, how fast it is, but according to my tests, it works.

**Comment by boxdot** [comment]
O(n log^2 n) algorithm is implemented. Next step would be the O(n log n) algorithm. I will do it in a different issue.
